#!/data/data/com.termux/files/usr/bin/bash
# =============================================================================
# ClipIt → scripts/boot_recovery.sh  (Agent 05: Mobile Daemon & OS Runtime)
# -----------------------------------------------------------------------------
# Automatic recovery: restarts the ClipIt daemon after the Android phone
# reboots. Designed for the Termux:Boot add-on:
#
#   ./boot_recovery.sh --install
#
# This writes ~/.termux/boot/clipit_boot.sh (a thin wrapper that calls THIS
# script by absolute path, so path resolution stays correct after install).
# Termux:Boot executes every file in ~/.termux/boot/ on device boot.
#
# The recovery flow:
#   - waits for boot to settle (avoids racing the storage mount)
#   - refuses to double-start if the daemon is already running
#   - re-acquires the wake-lock and relaunches daemon + monitor via start.sh
#
# Usage:  ./boot_recovery.sh [--install] [--force]
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
PID_FILE="${ROOT_DIR}/storage/clipit.pid"
BOOT_SETTLE_SEC=20
TERMUX_BOOT_DIR="${HOME}/.termux/boot"
WRAPPER_NAME="clipit_boot.sh"

log()  { echo "[${0##*/}] $(date '+%F %T') $*"; }

# ---------------------------------------------------------------------------
# TSK-A05-07: install the Termux:Boot auto-start service.
# ---------------------------------------------------------------------------
if [[ "${1:-}" == "--install" ]]; then
  if [[ ! -d "${TERMUX_BOOT_DIR}" ]]; then
    log "Termux:Boot directory not found at ${TERMUX_BOOT_DIR}."
    log "Install the 'Termux:Boot' add-on first (pkg install termux-boot)."
    exit 1
  fi
  WRAPPER="${TERMUX_BOOT_DIR}/${WRAPPER_NAME}"
  cat > "${WRAPPER}" <<EOF
#!/data/data/com.termux/files/usr/bin/bash
# Auto-generated by ClipIt boot_recovery.sh --install on $(date '+%F %T')
# Runs the ClipIt recovery routine on every device boot.
exec "${SCRIPT_DIR}/boot_recovery.sh"
EOF
  chmod +x "${WRAPPER}"
  log "Installed boot service: ${WRAPPER}"
  log "Verify with: ls -la ${TERMUX_BOOT_DIR}/"
  exit 0
fi

# ---------------------------------------------------------------------------
# Wait for the filesystem to settle after boot.
# ---------------------------------------------------------------------------
log "Waiting ${BOOT_SETTLE_SEC}s for boot to settle..."
sleep "${BOOT_SETTLE_SEC}"

# ---------------------------------------------------------------------------
# Single-instance guard: if start.sh is already running, do nothing.
# ---------------------------------------------------------------------------
if [[ -f "${PID_FILE}" ]]; then
  EXISTING_PID="$(cat "${PID_FILE}" 2>/dev/null || true)"
  if [[ -n "${EXISTING_PID}" ]] && kill -0 "${EXISTING_PID}" 2>/dev/null; then
    log "Daemon already running (PID ${EXISTING_PID}); skipping recovery."
    exit 0
  fi
  log "Removing stale PID file from before reboot."
  rm -f "${PID_FILE}"
fi

if [[ "${1:-}" != "--force" ]]; then
  # Only auto-start if the daemon entrypoint exists (built by Agent 01).
  if [[ ! -x "${ROOT_DIR}/main.py" && ! -f "${ROOT_DIR}/main.py" ]]; then
    log "main.py not present; nothing to recover yet."
    exit 0
  fi
fi

log "Recovering ClipIt daemon..."
"${SCRIPT_DIR}/start.sh" || log "start.sh exited non-zero — see ${ROOT_DIR}/storage/logs/daemon.log"
log "Recovery done."
